#!/bin/bash
set -e
adr_bin_dir="$(dirname "$0")"
eval "$("$(dirname "$0")/adr-config")"

cmd="$adr_bin_dir/adr-$1"

if [ -x "$cmd" ]
then
    "$cmd" "${@:2}"
else
    "$adr_bin_dir/adr-help"
    exit 1
fi
